services:
  mysql:
    image: mysql:8.0
    container_name: mysql_shoperyorganic
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: thuan@7771412
      MYSQL_DATABASE: shoperyorganic
      MYSQL_USER: user
      MYSQL_PASSWORD: thuan@7771412

    networks:
      - PrviNetwork

  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: cloudbeaver
    restart: always
    ports:
      - "8979:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - PrviNetwork

volumes:
  cloudbeaver-data:
  mysql-data:

networks:
  PrviNetwork:
    external: true